# https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#run-grafana-via-docker-compose
# https://docs.influxdata.com/influxdb/v2/install/use-docker-compose
# https://pimylifeup.com/mosquitto-mqtt-docker

name: zimmer-wetter

services:
  # ############################# #
  #     Mosquitto MQTT Broker     #
  # ############################# #
  broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: on-failure:5
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./config/mosquitto:/mosquitto/config
      - ./data/mosquitto:/mosquitto/data
    stdin_open: true
    tty: true

  # ############################# #
  # InfluxDB Time-Series Database #
  # ############################# #
  database:
    image: influxdb:alpine
    container_name: influxdb
    restart: on-failure:5
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_BUCKET: weather_data
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
    ports:
      - 8086:8086
    volumes:
      - ./config/influxdb:/etc/influxdb2
      - ./data/influxdb:/var/lib/influxdb2
    healthcheck:
      test: wget --no-verbose --tries=1 --output-document=/dev/null http://0.0.0.0:8086/ &> /dev/null || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  # ############################# #
  #  Weather Data Edge Function   #
  # ############################# #
  function:
    build: ./function
    container_name: function
    restart: on-failure:5
    environment:
      INFLUXDB_V2_URL: http://database:8086
      INFLUXDB_V2_TIMEOUT: 6000
    depends_on:
      - database
      - broker

  # ############################# #
  #     Chronograf Analytics      #
  # ############################# #
  analytics:
    image: chronograf:alpine
    container_name: chronograf
    restart: on-failure:5
    environment:
      INFLUXDB_URL: http://database:8086
    ports:
      - 8888:8888
    depends_on:
      - database
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    healthcheck:
      test: wget --no-verbose --tries=1 --output-document=/dev/null http://0.0.0.0:8888/ &> /dev/null || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
